#define KEY_ID 0x0001;

#define ISSUER_MAX_BATCHSIZE    3;
#define ISSUER_MAX_ISSUANCE     3;
#define ISSUER_PUBLIC_METADATA  0x0001;
#define ISSUER_PRIVATE_METADATA 0;
#define ISSUER_LIFETIME         180;

#define CLIENT_MAX_BATCHSIZE    3;
#define CLIENT_ISSUANCE_COUNT   3;
#define CLIENT_REDEMPTION_DATA  "HELLO WORLD";
#define CLIENT_REDEMPTION_TIME  13374242;
#define TOKEN_HASH  "TrustTokenV0 TokenHash";
